apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spring-boot-mon-app
spec:
  selector:
    matchLabels:
      app: spring-boot-mon-app
  replicas: 2 
  template: 
    metadata:
      labels:
        app: spring-boot-mon-app
    spec:
      containers:
      - name: spring-boot-mon-app
        image: renatofenrir/spring-boot-mon-app:v1
        ports:
        - containerPort: 9000
          name: server
